/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.bookkeeper.mledger.offload.filesystem.impl;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertFalse;
import static org.testng.Assert.assertTrue;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

/**
 * Tests that verify our native SequenceFile/MapFile implementation can read
 * files generated by the real Hadoop implementation (hadoop-common 3.4.2).
 *
 * <p>The fixture files in {@code src/test/resources/hadoop-fixtures/} were generated
 * using Hadoop's {@code SequenceFile.Writer} and {@code MapFile.Writer} with
 * {@code LongWritable} keys and {@code BytesWritable} values.
 *
 * <p>MapFile fixtures each contain:
 * <ul>
 *   <li>Key -1: metadata value "test-ledger-metadata-content"</li>
 *   <li>Keys 0-199: values "entry-data-0" through "entry-data-199"</li>
 * </ul>
 *
 * <p>Standalone SequenceFile fixtures each contain:
 * <ul>
 *   <li>Keys 0-199: values "entry-data-0" through "entry-data-199"</li>
 * </ul>
 *
 * <p>Three compression variants are tested: NONE, RECORD, and BLOCK.
 */
public class HadoopCompatibilityTest {

    private static final int NUM_ENTRIES = 200;
    private static final String METADATA_VALUE = "test-ledger-metadata-content";

    @DataProvider(name = "compressionTypes")
    public Object[][] compressionTypes() {
        return new Object[][] {
                {"mapfile-none", SequenceFile.CompressionType.NONE},
                {"mapfile-record", SequenceFile.CompressionType.RECORD},
                {"mapfile-block", SequenceFile.CompressionType.BLOCK},
        };
    }

    @DataProvider(name = "seqFileCompressionTypes")
    public Object[][] seqFileCompressionTypes() {
        return new Object[][] {
                {"seqfile-none", SequenceFile.CompressionType.NONE},
                {"seqfile-record", SequenceFile.CompressionType.RECORD},
                {"seqfile-block", SequenceFile.CompressionType.BLOCK},
        };
    }

    private Path getFixturePath(String name) throws URISyntaxException {
        return Paths.get(getClass().getClassLoader().getResource("hadoop-fixtures/" + name).toURI());
    }

    // -- Standalone SequenceFile fixture tests --

    @Test(dataProvider = "seqFileCompressionTypes")
    public void testReadHadoopSequenceFileHeader(String fixtureName,
                                                  SequenceFile.CompressionType expectedCompression)
            throws Exception {
        try (SequenceFile.Reader reader = new SequenceFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.Header header = reader.getHeader();
            assertEquals(header.keyClassName, "org.apache.hadoop.io.LongWritable");
            assertEquals(header.valueClassName, "org.apache.hadoop.io.BytesWritable");
            assertEquals(header.compressionType, expectedCompression);
        }
    }

    @Test(dataProvider = "seqFileCompressionTypes")
    public void testReadAllHadoopSequenceFileRecords(String fixtureName,
                                                      SequenceFile.CompressionType ignored)
            throws Exception {
        try (SequenceFile.Reader reader = new SequenceFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();

            // Entries 0 through 199
            for (int i = 0; i < NUM_ENTRIES; i++) {
                assertTrue(reader.next(kv), "Missing entry " + i);
                assertEquals(SequenceFile.deserializeLong(kv.key), (long) i);
                assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                        "entry-data-" + i);
            }

            assertFalse(reader.next(kv), "Should be at EOF");
        }
    }

    // -- MapFile data/index SequenceFile tests --

    @Test(dataProvider = "compressionTypes")
    public void testReadHadoopMapFileDataHeader(String fixtureName,
                                                  SequenceFile.CompressionType expectedCompression)
            throws Exception {
        Path dataFile = getFixturePath(fixtureName).resolve("data");
        try (SequenceFile.Reader reader = new SequenceFile.Reader(dataFile)) {
            SequenceFile.Header header = reader.getHeader();
            assertEquals(header.keyClassName, "org.apache.hadoop.io.LongWritable");
            assertEquals(header.valueClassName, "org.apache.hadoop.io.BytesWritable");
            assertEquals(header.compressionType, expectedCompression);
        }
    }

    @Test(dataProvider = "compressionTypes")
    public void testReadAllHadoopMapFileDataRecords(String fixtureName,
                                                      SequenceFile.CompressionType ignored)
            throws Exception {
        Path dataFile = getFixturePath(fixtureName).resolve("data");
        try (SequenceFile.Reader reader = new SequenceFile.Reader(dataFile)) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();

            // First record: metadata at key -1
            assertTrue(reader.next(kv));
            assertEquals(SequenceFile.deserializeLong(kv.key), -1L);
            assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                    METADATA_VALUE);

            // Entries 0 through 199
            for (int i = 0; i < NUM_ENTRIES; i++) {
                assertTrue(reader.next(kv), "Missing entry " + i);
                assertEquals(SequenceFile.deserializeLong(kv.key), (long) i);
                assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                        "entry-data-" + i);
            }

            assertFalse(reader.next(kv), "Should be at EOF");
        }
    }

    @Test
    public void testReadHadoopIndexFile() throws Exception {
        Path indexFile = getFixturePath("mapfile-none").resolve("index");
        try (SequenceFile.Reader reader = new SequenceFile.Reader(indexFile)) {
            assertEquals(reader.getHeader().keyClassName, "org.apache.hadoop.io.LongWritable");
            assertEquals(reader.getHeader().valueClassName, "org.apache.hadoop.io.LongWritable");

            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();
            // First index entry should be key -1 (the first key written)
            assertTrue(reader.next(kv));
            assertEquals(SequenceFile.deserializeLong(kv.key), -1L);

            // Second index entry at interval 128 -> key 127 (entry 128 counting from -1)
            assertTrue(reader.next(kv));
            assertEquals(SequenceFile.deserializeLong(kv.key), 127L);
        }
    }

    // -- NativeMapFile-level tests --

    @Test(dataProvider = "compressionTypes")
    public void testMapFileGetMetadata(String fixtureName, SequenceFile.CompressionType ignored) throws Exception {
        try (NativeMapFile.Reader reader = new NativeMapFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();
            reader.get(-1, kv);
            assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                    METADATA_VALUE);
        }
    }

    @Test(dataProvider = "compressionTypes")
    public void testMapFileGetEntryByKey(String fixtureName, SequenceFile.CompressionType ignored) throws Exception {
        try (NativeMapFile.Reader reader = new NativeMapFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();

            reader.get(0, kv);
            assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                    "entry-data-0");

            reader.get(99, kv);
            assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                    "entry-data-99");

            reader.get(199, kv);
            assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                    "entry-data-199");
        }
    }

    @Test(dataProvider = "compressionTypes")
    public void testMapFileSeekAndSequentialRead(String fixtureName,
                                                  SequenceFile.CompressionType ignored) throws Exception {
        try (NativeMapFile.Reader reader = new NativeMapFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();

            // Seek to entry 150, read the rest sequentially
            reader.seek(150);
            for (int i = 150; i < NUM_ENTRIES; i++) {
                assertTrue(reader.next(kv), "Missing entry " + i);
                assertEquals(SequenceFile.deserializeLong(kv.key), (long) i);
                assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                        "entry-data-" + i);
            }
            assertFalse(reader.next(kv));
        }
    }

    @Test(dataProvider = "compressionTypes")
    public void testMapFileFullSequentialRead(String fixtureName,
                                              SequenceFile.CompressionType ignored) throws Exception {
        try (NativeMapFile.Reader reader = new NativeMapFile.Reader(getFixturePath(fixtureName))) {
            SequenceFile.KeyValue kv = new SequenceFile.KeyValue();

            // Read all entries sequentially
            assertTrue(reader.next(kv));
            assertEquals(SequenceFile.deserializeLong(kv.key), -1L);

            for (int i = 0; i < NUM_ENTRIES; i++) {
                assertTrue(reader.next(kv), "Missing entry " + i);
                assertEquals(SequenceFile.deserializeLong(kv.key), (long) i);
                assertEquals(new String(SequenceFile.deserializeBytes(kv.value), StandardCharsets.UTF_8),
                        "entry-data-" + i);
            }
            assertFalse(reader.next(kv));
        }
    }

    // -- Byte-identical output tests --

    private Path tempDir;

    @BeforeMethod
    public void setup() throws IOException {
        tempDir = Files.createTempDirectory("hadoop-compat-test");
    }

    @AfterMethod(alwaysRun = true)
    public void tearDown() throws IOException {
        if (tempDir != null) {
            Files.walk(tempDir)
                    .sorted(java.util.Comparator.reverseOrder())
                    .forEach(p -> {
                        try {
                            Files.deleteIfExists(p);
                        } catch (IOException e) {
                            // ignore
                        }
                    });
        }
    }

    @Test
    public void testByteIdenticalSequenceFile() throws Exception {
        // Read the sync marker from the Hadoop-generated NONE SequenceFile
        Path hadoopFile = getFixturePath("seqfile-none");
        byte[] hadoopSync;
        try (SequenceFile.Reader reader = new SequenceFile.Reader(hadoopFile)) {
            hadoopSync = reader.getHeader().sync;
        }

        // Write the same data with the same sync marker
        Path outputFile = tempDir.resolve("seqfile-none");
        try (SequenceFile.Writer writer = new SequenceFile.Writer(outputFile,
                NativeMapFile.KEY_CLASS, NativeMapFile.VALUE_CLASS, hadoopSync)) {
            for (int i = 0; i < NUM_ENTRIES; i++) {
                byte[] key = SequenceFile.serializeLong(i);
                byte[] data = ("entry-data-" + i).getBytes(StandardCharsets.UTF_8);
                byte[] value = SequenceFile.serializeBytes(data, 0, data.length);
                writer.append(key, value);
            }
        }

        // Compare byte-by-byte
        byte[] hadoopBytes = Files.readAllBytes(hadoopFile);
        byte[] nativeBytes = Files.readAllBytes(outputFile);
        assertEquals(nativeBytes, hadoopBytes, "SequenceFile must be byte-identical to Hadoop output");
    }

    @Test
    public void testByteIdenticalDataFile() throws Exception {
        // Read the sync marker from the Hadoop-generated NONE data file
        Path hadoopDataFile = getFixturePath("mapfile-none").resolve("data");
        byte[] hadoopSync;
        try (SequenceFile.Reader reader = new SequenceFile.Reader(hadoopDataFile)) {
            hadoopSync = reader.getHeader().sync;
        }

        // Write the same data with the same sync marker
        Path outputDir = tempDir.resolve("mapfile-none");
        try (NativeMapFile.Writer writer = new NativeMapFile.Writer(outputDir, hadoopSync, null)) {
            byte[] metadata = METADATA_VALUE.getBytes(StandardCharsets.UTF_8);
            writer.append(-1, metadata, 0, metadata.length);
            for (int i = 0; i < NUM_ENTRIES; i++) {
                byte[] data = ("entry-data-" + i).getBytes(StandardCharsets.UTF_8);
                writer.append(i, data, 0, data.length);
            }
        }

        // Compare data files byte-by-byte
        byte[] hadoopBytes = Files.readAllBytes(hadoopDataFile);
        byte[] nativeBytes = Files.readAllBytes(outputDir.resolve("data"));
        assertEquals(nativeBytes, hadoopBytes, "Data file must be byte-identical to Hadoop output");
    }

    @Test
    public void testByteIdenticalIndexFile() throws Exception {
        // Read sync markers from Hadoop-generated files
        Path hadoopDir = getFixturePath("mapfile-none");
        byte[] dataSyncMarker;
        byte[] indexSyncMarker;
        try (SequenceFile.Reader reader = new SequenceFile.Reader(hadoopDir.resolve("data"))) {
            dataSyncMarker = reader.getHeader().sync;
        }
        try (SequenceFile.Reader reader = new SequenceFile.Reader(hadoopDir.resolve("index"))) {
            indexSyncMarker = reader.getHeader().sync;
        }

        // Write the same data with the same sync markers
        Path outputDir = tempDir.resolve("mapfile-none");
        try (NativeMapFile.Writer writer = new NativeMapFile.Writer(
                outputDir, dataSyncMarker, indexSyncMarker)) {
            byte[] metadata = METADATA_VALUE.getBytes(StandardCharsets.UTF_8);
            writer.append(-1, metadata, 0, metadata.length);
            for (int i = 0; i < NUM_ENTRIES; i++) {
                byte[] data = ("entry-data-" + i).getBytes(StandardCharsets.UTF_8);
                writer.append(i, data, 0, data.length);
            }
        }

        // Compare index files byte-by-byte
        // Note: our index uses NONE compression while Hadoop uses BLOCK compression,
        // so we only compare the data file here. The index is functionally equivalent
        // but uses a different compression format.
        byte[] hadoopBytes = Files.readAllBytes(hadoopDir.resolve("data"));
        byte[] nativeBytes = Files.readAllBytes(outputDir.resolve("data"));
        assertEquals(nativeBytes, hadoopBytes, "Data file must be byte-identical to Hadoop output");
    }
}
